# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tox', [dirname(__file__)])
        except ImportError:
            import _tox
            return _tox
        if fp is not None:
            try:
                _mod = imp.load_module('_tox', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tox = swig_import_helper()
    del swig_import_helper
else:
    import _tox
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


MAX_NAME_LENGTH = _tox.MAX_NAME_LENGTH
MAX_STATUSMESSAGE_LENGTH = _tox.MAX_STATUSMESSAGE_LENGTH
PACKET_ID_ALIVE = _tox.PACKET_ID_ALIVE
PACKET_ID_SHARE_RELAYS = _tox.PACKET_ID_SHARE_RELAYS
PACKET_ID_NICKNAME = _tox.PACKET_ID_NICKNAME
PACKET_ID_STATUSMESSAGE = _tox.PACKET_ID_STATUSMESSAGE
PACKET_ID_USERSTATUS = _tox.PACKET_ID_USERSTATUS
PACKET_ID_TYPING = _tox.PACKET_ID_TYPING
PACKET_ID_RECEIPT = _tox.PACKET_ID_RECEIPT
PACKET_ID_MESSAGE = _tox.PACKET_ID_MESSAGE
PACKET_ID_ACTION = _tox.PACKET_ID_ACTION
PACKET_ID_MSI = _tox.PACKET_ID_MSI
PACKET_ID_FILE_SENDREQUEST = _tox.PACKET_ID_FILE_SENDREQUEST
PACKET_ID_FILE_CONTROL = _tox.PACKET_ID_FILE_CONTROL
PACKET_ID_FILE_DATA = _tox.PACKET_ID_FILE_DATA
PACKET_ID_INVITE_GROUPCHAT = _tox.PACKET_ID_INVITE_GROUPCHAT
PACKET_ID_JOIN_GROUPCHAT = _tox.PACKET_ID_JOIN_GROUPCHAT
PACKET_ID_ACCEPT_GROUPCHAT = _tox.PACKET_ID_ACCEPT_GROUPCHAT
MAX_INVITED_GROUPS = _tox.MAX_INVITED_GROUPS
MAX_SHARED_RELAYS = _tox.MAX_SHARED_RELAYS
PACKET_ID_LOSSLESS_RANGE_START = _tox.PACKET_ID_LOSSLESS_RANGE_START
PACKET_ID_LOSSLESS_RANGE_SIZE = _tox.PACKET_ID_LOSSLESS_RANGE_SIZE
NOFRIEND = _tox.NOFRIEND
FRIEND_ADDED = _tox.FRIEND_ADDED
FRIEND_REQUESTED = _tox.FRIEND_REQUESTED
FRIEND_CONFIRMED = _tox.FRIEND_CONFIRMED
FRIEND_ONLINE = _tox.FRIEND_ONLINE
FAERR_TOOLONG = _tox.FAERR_TOOLONG
FAERR_NOMESSAGE = _tox.FAERR_NOMESSAGE
FAERR_OWNKEY = _tox.FAERR_OWNKEY
FAERR_ALREADYSENT = _tox.FAERR_ALREADYSENT
FAERR_UNKNOWN = _tox.FAERR_UNKNOWN
FAERR_BADCHECKSUM = _tox.FAERR_BADCHECKSUM
FAERR_SETNEWNOSPAM = _tox.FAERR_SETNEWNOSPAM
FAERR_NOMEM = _tox.FAERR_NOMEM
FRIENDREQUEST_TIMEOUT = _tox.FRIENDREQUEST_TIMEOUT
FRIEND_PING_INTERVAL = _tox.FRIEND_PING_INTERVAL
FRIEND_SHARE_RELAYS_INTERVAL = _tox.FRIEND_SHARE_RELAYS_INTERVAL
FRIEND_CONNECTION_TIMEOUT = _tox.FRIEND_CONNECTION_TIMEOUT
USERSTATUS_NONE = _tox.USERSTATUS_NONE
USERSTATUS_AWAY = _tox.USERSTATUS_AWAY
USERSTATUS_BUSY = _tox.USERSTATUS_BUSY
USERSTATUS_INVALID = _tox.USERSTATUS_INVALID
class File_Transfers(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, File_Transfers, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, File_Transfers, name)
    __repr__ = _swig_repr
    __swig_setmethods__["size"] = _tox.File_Transfers_size_set
    __swig_getmethods__["size"] = _tox.File_Transfers_size_get
    if _newclass:size = _swig_property(_tox.File_Transfers_size_get, _tox.File_Transfers_size_set)
    __swig_setmethods__["transferred"] = _tox.File_Transfers_transferred_set
    __swig_getmethods__["transferred"] = _tox.File_Transfers_transferred_get
    if _newclass:transferred = _swig_property(_tox.File_Transfers_transferred_get, _tox.File_Transfers_transferred_set)
    __swig_setmethods__["status"] = _tox.File_Transfers_status_set
    __swig_getmethods__["status"] = _tox.File_Transfers_status_get
    if _newclass:status = _swig_property(_tox.File_Transfers_status_get, _tox.File_Transfers_status_set)
    def __init__(self): 
        this = _tox.new_File_Transfers()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tox.delete_File_Transfers
    __del__ = lambda self : None;
File_Transfers_swigregister = _tox.File_Transfers_swigregister
File_Transfers_swigregister(File_Transfers)

FILESTATUS_NONE = _tox.FILESTATUS_NONE
FILESTATUS_NOT_ACCEPTED = _tox.FILESTATUS_NOT_ACCEPTED
FILESTATUS_PAUSED_BY_OTHER = _tox.FILESTATUS_PAUSED_BY_OTHER
FILESTATUS_TRANSFERRING = _tox.FILESTATUS_TRANSFERRING
FILESTATUS_BROKEN = _tox.FILESTATUS_BROKEN
FILESTATUS_PAUSED_BY_US = _tox.FILESTATUS_PAUSED_BY_US
FILESTATUS_TEMPORARY = _tox.FILESTATUS_TEMPORARY
MAX_CONCURRENT_FILE_PIPES = _tox.MAX_CONCURRENT_FILE_PIPES
FILECONTROL_ACCEPT = _tox.FILECONTROL_ACCEPT
FILECONTROL_PAUSE = _tox.FILECONTROL_PAUSE
FILECONTROL_KILL = _tox.FILECONTROL_KILL
FILECONTROL_FINISHED = _tox.FILECONTROL_FINISHED
FILECONTROL_RESUME_BROKEN = _tox.FILECONTROL_RESUME_BROKEN
class Friend(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Friend, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Friend, name)
    __repr__ = _swig_repr
    __swig_setmethods__["client_id"] = _tox.Friend_client_id_set
    __swig_getmethods__["client_id"] = _tox.Friend_client_id_get
    if _newclass:client_id = _swig_property(_tox.Friend_client_id_get, _tox.Friend_client_id_set)
    __swig_setmethods__["onion_friendnum"] = _tox.Friend_onion_friendnum_set
    __swig_getmethods__["onion_friendnum"] = _tox.Friend_onion_friendnum_get
    if _newclass:onion_friendnum = _swig_property(_tox.Friend_onion_friendnum_get, _tox.Friend_onion_friendnum_set)
    __swig_setmethods__["crypt_connection_id"] = _tox.Friend_crypt_connection_id_set
    __swig_getmethods__["crypt_connection_id"] = _tox.Friend_crypt_connection_id_get
    if _newclass:crypt_connection_id = _swig_property(_tox.Friend_crypt_connection_id_get, _tox.Friend_crypt_connection_id_set)
    __swig_setmethods__["friendrequest_lastsent"] = _tox.Friend_friendrequest_lastsent_set
    __swig_getmethods__["friendrequest_lastsent"] = _tox.Friend_friendrequest_lastsent_get
    if _newclass:friendrequest_lastsent = _swig_property(_tox.Friend_friendrequest_lastsent_get, _tox.Friend_friendrequest_lastsent_set)
    __swig_setmethods__["friendrequest_timeout"] = _tox.Friend_friendrequest_timeout_set
    __swig_getmethods__["friendrequest_timeout"] = _tox.Friend_friendrequest_timeout_get
    if _newclass:friendrequest_timeout = _swig_property(_tox.Friend_friendrequest_timeout_get, _tox.Friend_friendrequest_timeout_set)
    __swig_setmethods__["status"] = _tox.Friend_status_set
    __swig_getmethods__["status"] = _tox.Friend_status_get
    if _newclass:status = _swig_property(_tox.Friend_status_get, _tox.Friend_status_set)
    __swig_setmethods__["info"] = _tox.Friend_info_set
    __swig_getmethods__["info"] = _tox.Friend_info_get
    if _newclass:info = _swig_property(_tox.Friend_info_get, _tox.Friend_info_set)
    __swig_setmethods__["name"] = _tox.Friend_name_set
    __swig_getmethods__["name"] = _tox.Friend_name_get
    if _newclass:name = _swig_property(_tox.Friend_name_get, _tox.Friend_name_set)
    __swig_setmethods__["name_length"] = _tox.Friend_name_length_set
    __swig_getmethods__["name_length"] = _tox.Friend_name_length_get
    if _newclass:name_length = _swig_property(_tox.Friend_name_length_get, _tox.Friend_name_length_set)
    __swig_setmethods__["name_sent"] = _tox.Friend_name_sent_set
    __swig_getmethods__["name_sent"] = _tox.Friend_name_sent_get
    if _newclass:name_sent = _swig_property(_tox.Friend_name_sent_get, _tox.Friend_name_sent_set)
    __swig_setmethods__["statusmessage"] = _tox.Friend_statusmessage_set
    __swig_getmethods__["statusmessage"] = _tox.Friend_statusmessage_get
    if _newclass:statusmessage = _swig_property(_tox.Friend_statusmessage_get, _tox.Friend_statusmessage_set)
    __swig_setmethods__["statusmessage_length"] = _tox.Friend_statusmessage_length_set
    __swig_getmethods__["statusmessage_length"] = _tox.Friend_statusmessage_length_get
    if _newclass:statusmessage_length = _swig_property(_tox.Friend_statusmessage_length_get, _tox.Friend_statusmessage_length_set)
    __swig_setmethods__["statusmessage_sent"] = _tox.Friend_statusmessage_sent_set
    __swig_getmethods__["statusmessage_sent"] = _tox.Friend_statusmessage_sent_get
    if _newclass:statusmessage_sent = _swig_property(_tox.Friend_statusmessage_sent_get, _tox.Friend_statusmessage_sent_set)
    __swig_setmethods__["userstatus"] = _tox.Friend_userstatus_set
    __swig_getmethods__["userstatus"] = _tox.Friend_userstatus_get
    if _newclass:userstatus = _swig_property(_tox.Friend_userstatus_get, _tox.Friend_userstatus_set)
    __swig_setmethods__["userstatus_sent"] = _tox.Friend_userstatus_sent_set
    __swig_getmethods__["userstatus_sent"] = _tox.Friend_userstatus_sent_get
    if _newclass:userstatus_sent = _swig_property(_tox.Friend_userstatus_sent_get, _tox.Friend_userstatus_sent_set)
    __swig_setmethods__["user_istyping"] = _tox.Friend_user_istyping_set
    __swig_getmethods__["user_istyping"] = _tox.Friend_user_istyping_get
    if _newclass:user_istyping = _swig_property(_tox.Friend_user_istyping_get, _tox.Friend_user_istyping_set)
    __swig_setmethods__["user_istyping_sent"] = _tox.Friend_user_istyping_sent_set
    __swig_getmethods__["user_istyping_sent"] = _tox.Friend_user_istyping_sent_get
    if _newclass:user_istyping_sent = _swig_property(_tox.Friend_user_istyping_sent_get, _tox.Friend_user_istyping_sent_set)
    __swig_setmethods__["is_typing"] = _tox.Friend_is_typing_set
    __swig_getmethods__["is_typing"] = _tox.Friend_is_typing_get
    if _newclass:is_typing = _swig_property(_tox.Friend_is_typing_get, _tox.Friend_is_typing_set)
    __swig_setmethods__["info_size"] = _tox.Friend_info_size_set
    __swig_getmethods__["info_size"] = _tox.Friend_info_size_get
    if _newclass:info_size = _swig_property(_tox.Friend_info_size_get, _tox.Friend_info_size_set)
    __swig_setmethods__["message_id"] = _tox.Friend_message_id_set
    __swig_getmethods__["message_id"] = _tox.Friend_message_id_get
    if _newclass:message_id = _swig_property(_tox.Friend_message_id_get, _tox.Friend_message_id_set)
    __swig_setmethods__["receives_read_receipts"] = _tox.Friend_receives_read_receipts_set
    __swig_getmethods__["receives_read_receipts"] = _tox.Friend_receives_read_receipts_get
    if _newclass:receives_read_receipts = _swig_property(_tox.Friend_receives_read_receipts_get, _tox.Friend_receives_read_receipts_set)
    __swig_setmethods__["friendrequest_nospam"] = _tox.Friend_friendrequest_nospam_set
    __swig_getmethods__["friendrequest_nospam"] = _tox.Friend_friendrequest_nospam_get
    if _newclass:friendrequest_nospam = _swig_property(_tox.Friend_friendrequest_nospam_get, _tox.Friend_friendrequest_nospam_set)
    __swig_setmethods__["ping_lastrecv"] = _tox.Friend_ping_lastrecv_set
    __swig_getmethods__["ping_lastrecv"] = _tox.Friend_ping_lastrecv_get
    if _newclass:ping_lastrecv = _swig_property(_tox.Friend_ping_lastrecv_get, _tox.Friend_ping_lastrecv_set)
    __swig_setmethods__["ping_lastsent"] = _tox.Friend_ping_lastsent_set
    __swig_getmethods__["ping_lastsent"] = _tox.Friend_ping_lastsent_get
    if _newclass:ping_lastsent = _swig_property(_tox.Friend_ping_lastsent_get, _tox.Friend_ping_lastsent_set)
    __swig_setmethods__["share_relays_lastsent"] = _tox.Friend_share_relays_lastsent_set
    __swig_getmethods__["share_relays_lastsent"] = _tox.Friend_share_relays_lastsent_get
    if _newclass:share_relays_lastsent = _swig_property(_tox.Friend_share_relays_lastsent_get, _tox.Friend_share_relays_lastsent_set)
    __swig_setmethods__["file_sending"] = _tox.Friend_file_sending_set
    __swig_getmethods__["file_sending"] = _tox.Friend_file_sending_get
    if _newclass:file_sending = _swig_property(_tox.Friend_file_sending_get, _tox.Friend_file_sending_set)
    __swig_setmethods__["file_receiving"] = _tox.Friend_file_receiving_set
    __swig_getmethods__["file_receiving"] = _tox.Friend_file_receiving_get
    if _newclass:file_receiving = _swig_property(_tox.Friend_file_receiving_get, _tox.Friend_file_receiving_set)
    __swig_setmethods__["invited_groups"] = _tox.Friend_invited_groups_set
    __swig_getmethods__["invited_groups"] = _tox.Friend_invited_groups_get
    if _newclass:invited_groups = _swig_property(_tox.Friend_invited_groups_get, _tox.Friend_invited_groups_set)
    __swig_setmethods__["invited_groups_num"] = _tox.Friend_invited_groups_num_set
    __swig_getmethods__["invited_groups_num"] = _tox.Friend_invited_groups_num_get
    if _newclass:invited_groups_num = _swig_property(_tox.Friend_invited_groups_num_get, _tox.Friend_invited_groups_num_set)
    __swig_getmethods__["lossy_packethandlers"] = _tox.Friend_lossy_packethandlers_get
    if _newclass:lossy_packethandlers = _swig_property(_tox.Friend_lossy_packethandlers_get)
    __swig_getmethods__["lossless_packethandlers"] = _tox.Friend_lossless_packethandlers_get
    if _newclass:lossless_packethandlers = _swig_property(_tox.Friend_lossless_packethandlers_get)
    def __init__(self): 
        this = _tox.new_Friend()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tox.delete_Friend
    __del__ = lambda self : None;
Friend_swigregister = _tox.Friend_swigregister
Friend_swigregister(Friend)

class Friend_lossless_packethandlers(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Friend_lossless_packethandlers, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Friend_lossless_packethandlers, name)
    __repr__ = _swig_repr
    __swig_setmethods__["function"] = _tox.Friend_lossless_packethandlers_function_set
    __swig_getmethods__["function"] = _tox.Friend_lossless_packethandlers_function_get
    if _newclass:function = _swig_property(_tox.Friend_lossless_packethandlers_function_get, _tox.Friend_lossless_packethandlers_function_set)
    __swig_setmethods__["object"] = _tox.Friend_lossless_packethandlers_object_set
    __swig_getmethods__["object"] = _tox.Friend_lossless_packethandlers_object_get
    if _newclass:object = _swig_property(_tox.Friend_lossless_packethandlers_object_get, _tox.Friend_lossless_packethandlers_object_set)
    def __init__(self): 
        this = _tox.new_Friend_lossless_packethandlers()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tox.delete_Friend_lossless_packethandlers
    __del__ = lambda self : None;
Friend_lossless_packethandlers_swigregister = _tox.Friend_lossless_packethandlers_swigregister
Friend_lossless_packethandlers_swigregister(Friend_lossless_packethandlers)

class Friend_lossy_packethandlers(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Friend_lossy_packethandlers, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Friend_lossy_packethandlers, name)
    __repr__ = _swig_repr
    __swig_setmethods__["function"] = _tox.Friend_lossy_packethandlers_function_set
    __swig_getmethods__["function"] = _tox.Friend_lossy_packethandlers_function_get
    if _newclass:function = _swig_property(_tox.Friend_lossy_packethandlers_function_get, _tox.Friend_lossy_packethandlers_function_set)
    __swig_setmethods__["object"] = _tox.Friend_lossy_packethandlers_object_set
    __swig_getmethods__["object"] = _tox.Friend_lossy_packethandlers_object_get
    if _newclass:object = _swig_property(_tox.Friend_lossy_packethandlers_object_get, _tox.Friend_lossy_packethandlers_object_set)
    def __init__(self): 
        this = _tox.new_Friend_lossy_packethandlers()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tox.delete_Friend_lossy_packethandlers
    __del__ = lambda self : None;
Friend_lossy_packethandlers_swigregister = _tox.Friend_lossy_packethandlers_swigregister
Friend_lossy_packethandlers_swigregister(Friend_lossy_packethandlers)

class Messenger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Messenger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Messenger, name)
    __repr__ = _swig_repr
    __swig_setmethods__["net"] = _tox.Messenger_net_set
    __swig_getmethods__["net"] = _tox.Messenger_net_get
    if _newclass:net = _swig_property(_tox.Messenger_net_get, _tox.Messenger_net_set)
    __swig_setmethods__["net_crypto"] = _tox.Messenger_net_crypto_set
    __swig_getmethods__["net_crypto"] = _tox.Messenger_net_crypto_get
    if _newclass:net_crypto = _swig_property(_tox.Messenger_net_crypto_get, _tox.Messenger_net_crypto_set)
    __swig_setmethods__["dht"] = _tox.Messenger_dht_set
    __swig_getmethods__["dht"] = _tox.Messenger_dht_get
    if _newclass:dht = _swig_property(_tox.Messenger_dht_get, _tox.Messenger_dht_set)
    __swig_setmethods__["onion"] = _tox.Messenger_onion_set
    __swig_getmethods__["onion"] = _tox.Messenger_onion_get
    if _newclass:onion = _swig_property(_tox.Messenger_onion_get, _tox.Messenger_onion_set)
    __swig_setmethods__["onion_a"] = _tox.Messenger_onion_a_set
    __swig_getmethods__["onion_a"] = _tox.Messenger_onion_a_get
    if _newclass:onion_a = _swig_property(_tox.Messenger_onion_a_get, _tox.Messenger_onion_a_set)
    __swig_setmethods__["onion_c"] = _tox.Messenger_onion_c_set
    __swig_getmethods__["onion_c"] = _tox.Messenger_onion_c_get
    if _newclass:onion_c = _swig_property(_tox.Messenger_onion_c_get, _tox.Messenger_onion_c_set)
    __swig_setmethods__["fr"] = _tox.Messenger_fr_set
    __swig_getmethods__["fr"] = _tox.Messenger_fr_get
    if _newclass:fr = _swig_property(_tox.Messenger_fr_get, _tox.Messenger_fr_set)
    __swig_setmethods__["name"] = _tox.Messenger_name_set
    __swig_getmethods__["name"] = _tox.Messenger_name_get
    if _newclass:name = _swig_property(_tox.Messenger_name_get, _tox.Messenger_name_set)
    __swig_setmethods__["name_length"] = _tox.Messenger_name_length_set
    __swig_getmethods__["name_length"] = _tox.Messenger_name_length_get
    if _newclass:name_length = _swig_property(_tox.Messenger_name_length_get, _tox.Messenger_name_length_set)
    __swig_setmethods__["statusmessage"] = _tox.Messenger_statusmessage_set
    __swig_getmethods__["statusmessage"] = _tox.Messenger_statusmessage_get
    if _newclass:statusmessage = _swig_property(_tox.Messenger_statusmessage_get, _tox.Messenger_statusmessage_set)
    __swig_setmethods__["statusmessage_length"] = _tox.Messenger_statusmessage_length_set
    __swig_getmethods__["statusmessage_length"] = _tox.Messenger_statusmessage_length_get
    if _newclass:statusmessage_length = _swig_property(_tox.Messenger_statusmessage_length_get, _tox.Messenger_statusmessage_length_set)
    __swig_setmethods__["userstatus"] = _tox.Messenger_userstatus_set
    __swig_getmethods__["userstatus"] = _tox.Messenger_userstatus_get
    if _newclass:userstatus = _swig_property(_tox.Messenger_userstatus_get, _tox.Messenger_userstatus_set)
    __swig_setmethods__["friendlist"] = _tox.Messenger_friendlist_set
    __swig_getmethods__["friendlist"] = _tox.Messenger_friendlist_get
    if _newclass:friendlist = _swig_property(_tox.Messenger_friendlist_get, _tox.Messenger_friendlist_set)
    __swig_setmethods__["numfriends"] = _tox.Messenger_numfriends_set
    __swig_getmethods__["numfriends"] = _tox.Messenger_numfriends_get
    if _newclass:numfriends = _swig_property(_tox.Messenger_numfriends_get, _tox.Messenger_numfriends_set)
    __swig_setmethods__["numonline_friends"] = _tox.Messenger_numonline_friends_set
    __swig_getmethods__["numonline_friends"] = _tox.Messenger_numonline_friends_get
    if _newclass:numonline_friends = _swig_property(_tox.Messenger_numonline_friends_get, _tox.Messenger_numonline_friends_set)
    __swig_setmethods__["chats"] = _tox.Messenger_chats_set
    __swig_getmethods__["chats"] = _tox.Messenger_chats_get
    if _newclass:chats = _swig_property(_tox.Messenger_chats_get, _tox.Messenger_chats_set)
    __swig_setmethods__["numchats"] = _tox.Messenger_numchats_set
    __swig_getmethods__["numchats"] = _tox.Messenger_numchats_get
    if _newclass:numchats = _swig_property(_tox.Messenger_numchats_get, _tox.Messenger_numchats_set)
    __swig_setmethods__["last_LANdiscovery"] = _tox.Messenger_last_LANdiscovery_set
    __swig_getmethods__["last_LANdiscovery"] = _tox.Messenger_last_LANdiscovery_get
    if _newclass:last_LANdiscovery = _swig_property(_tox.Messenger_last_LANdiscovery_get, _tox.Messenger_last_LANdiscovery_set)
    __swig_setmethods__["friend_message"] = _tox.Messenger_friend_message_set
    __swig_getmethods__["friend_message"] = _tox.Messenger_friend_message_get
    if _newclass:friend_message = _swig_property(_tox.Messenger_friend_message_get, _tox.Messenger_friend_message_set)
    __swig_setmethods__["friend_message_userdata"] = _tox.Messenger_friend_message_userdata_set
    __swig_getmethods__["friend_message_userdata"] = _tox.Messenger_friend_message_userdata_get
    if _newclass:friend_message_userdata = _swig_property(_tox.Messenger_friend_message_userdata_get, _tox.Messenger_friend_message_userdata_set)
    __swig_setmethods__["friend_action"] = _tox.Messenger_friend_action_set
    __swig_getmethods__["friend_action"] = _tox.Messenger_friend_action_get
    if _newclass:friend_action = _swig_property(_tox.Messenger_friend_action_get, _tox.Messenger_friend_action_set)
    __swig_setmethods__["friend_action_userdata"] = _tox.Messenger_friend_action_userdata_set
    __swig_getmethods__["friend_action_userdata"] = _tox.Messenger_friend_action_userdata_get
    if _newclass:friend_action_userdata = _swig_property(_tox.Messenger_friend_action_userdata_get, _tox.Messenger_friend_action_userdata_set)
    __swig_setmethods__["friend_namechange"] = _tox.Messenger_friend_namechange_set
    __swig_getmethods__["friend_namechange"] = _tox.Messenger_friend_namechange_get
    if _newclass:friend_namechange = _swig_property(_tox.Messenger_friend_namechange_get, _tox.Messenger_friend_namechange_set)
    __swig_setmethods__["friend_namechange_userdata"] = _tox.Messenger_friend_namechange_userdata_set
    __swig_getmethods__["friend_namechange_userdata"] = _tox.Messenger_friend_namechange_userdata_get
    if _newclass:friend_namechange_userdata = _swig_property(_tox.Messenger_friend_namechange_userdata_get, _tox.Messenger_friend_namechange_userdata_set)
    __swig_setmethods__["friend_statusmessagechange"] = _tox.Messenger_friend_statusmessagechange_set
    __swig_getmethods__["friend_statusmessagechange"] = _tox.Messenger_friend_statusmessagechange_get
    if _newclass:friend_statusmessagechange = _swig_property(_tox.Messenger_friend_statusmessagechange_get, _tox.Messenger_friend_statusmessagechange_set)
    __swig_setmethods__["friend_statusmessagechange_userdata"] = _tox.Messenger_friend_statusmessagechange_userdata_set
    __swig_getmethods__["friend_statusmessagechange_userdata"] = _tox.Messenger_friend_statusmessagechange_userdata_get
    if _newclass:friend_statusmessagechange_userdata = _swig_property(_tox.Messenger_friend_statusmessagechange_userdata_get, _tox.Messenger_friend_statusmessagechange_userdata_set)
    __swig_setmethods__["friend_userstatuschange"] = _tox.Messenger_friend_userstatuschange_set
    __swig_getmethods__["friend_userstatuschange"] = _tox.Messenger_friend_userstatuschange_get
    if _newclass:friend_userstatuschange = _swig_property(_tox.Messenger_friend_userstatuschange_get, _tox.Messenger_friend_userstatuschange_set)
    __swig_setmethods__["friend_userstatuschange_userdata"] = _tox.Messenger_friend_userstatuschange_userdata_set
    __swig_getmethods__["friend_userstatuschange_userdata"] = _tox.Messenger_friend_userstatuschange_userdata_get
    if _newclass:friend_userstatuschange_userdata = _swig_property(_tox.Messenger_friend_userstatuschange_userdata_get, _tox.Messenger_friend_userstatuschange_userdata_set)
    __swig_setmethods__["friend_typingchange"] = _tox.Messenger_friend_typingchange_set
    __swig_getmethods__["friend_typingchange"] = _tox.Messenger_friend_typingchange_get
    if _newclass:friend_typingchange = _swig_property(_tox.Messenger_friend_typingchange_get, _tox.Messenger_friend_typingchange_set)
    __swig_setmethods__["friend_typingchange_userdata"] = _tox.Messenger_friend_typingchange_userdata_set
    __swig_getmethods__["friend_typingchange_userdata"] = _tox.Messenger_friend_typingchange_userdata_get
    if _newclass:friend_typingchange_userdata = _swig_property(_tox.Messenger_friend_typingchange_userdata_get, _tox.Messenger_friend_typingchange_userdata_set)
    __swig_setmethods__["read_receipt"] = _tox.Messenger_read_receipt_set
    __swig_getmethods__["read_receipt"] = _tox.Messenger_read_receipt_get
    if _newclass:read_receipt = _swig_property(_tox.Messenger_read_receipt_get, _tox.Messenger_read_receipt_set)
    __swig_setmethods__["read_receipt_userdata"] = _tox.Messenger_read_receipt_userdata_set
    __swig_getmethods__["read_receipt_userdata"] = _tox.Messenger_read_receipt_userdata_get
    if _newclass:read_receipt_userdata = _swig_property(_tox.Messenger_read_receipt_userdata_get, _tox.Messenger_read_receipt_userdata_set)
    __swig_setmethods__["friend_statuschange"] = _tox.Messenger_friend_statuschange_set
    __swig_getmethods__["friend_statuschange"] = _tox.Messenger_friend_statuschange_get
    if _newclass:friend_statuschange = _swig_property(_tox.Messenger_friend_statuschange_get, _tox.Messenger_friend_statuschange_set)
    __swig_setmethods__["friend_statuschange_userdata"] = _tox.Messenger_friend_statuschange_userdata_set
    __swig_getmethods__["friend_statuschange_userdata"] = _tox.Messenger_friend_statuschange_userdata_get
    if _newclass:friend_statuschange_userdata = _swig_property(_tox.Messenger_friend_statuschange_userdata_get, _tox.Messenger_friend_statuschange_userdata_set)
    __swig_setmethods__["friend_connectionstatuschange"] = _tox.Messenger_friend_connectionstatuschange_set
    __swig_getmethods__["friend_connectionstatuschange"] = _tox.Messenger_friend_connectionstatuschange_get
    if _newclass:friend_connectionstatuschange = _swig_property(_tox.Messenger_friend_connectionstatuschange_get, _tox.Messenger_friend_connectionstatuschange_set)
    __swig_setmethods__["friend_connectionstatuschange_userdata"] = _tox.Messenger_friend_connectionstatuschange_userdata_set
    __swig_getmethods__["friend_connectionstatuschange_userdata"] = _tox.Messenger_friend_connectionstatuschange_userdata_get
    if _newclass:friend_connectionstatuschange_userdata = _swig_property(_tox.Messenger_friend_connectionstatuschange_userdata_get, _tox.Messenger_friend_connectionstatuschange_userdata_set)
    __swig_setmethods__["friend_connectionstatuschange_internal"] = _tox.Messenger_friend_connectionstatuschange_internal_set
    __swig_getmethods__["friend_connectionstatuschange_internal"] = _tox.Messenger_friend_connectionstatuschange_internal_get
    if _newclass:friend_connectionstatuschange_internal = _swig_property(_tox.Messenger_friend_connectionstatuschange_internal_get, _tox.Messenger_friend_connectionstatuschange_internal_set)
    __swig_setmethods__["friend_connectionstatuschange_internal_userdata"] = _tox.Messenger_friend_connectionstatuschange_internal_userdata_set
    __swig_getmethods__["friend_connectionstatuschange_internal_userdata"] = _tox.Messenger_friend_connectionstatuschange_internal_userdata_get
    if _newclass:friend_connectionstatuschange_internal_userdata = _swig_property(_tox.Messenger_friend_connectionstatuschange_internal_userdata_get, _tox.Messenger_friend_connectionstatuschange_internal_userdata_set)
    __swig_setmethods__["group_invite"] = _tox.Messenger_group_invite_set
    __swig_getmethods__["group_invite"] = _tox.Messenger_group_invite_get
    if _newclass:group_invite = _swig_property(_tox.Messenger_group_invite_get, _tox.Messenger_group_invite_set)
    __swig_setmethods__["group_invite_userdata"] = _tox.Messenger_group_invite_userdata_set
    __swig_getmethods__["group_invite_userdata"] = _tox.Messenger_group_invite_userdata_get
    if _newclass:group_invite_userdata = _swig_property(_tox.Messenger_group_invite_userdata_get, _tox.Messenger_group_invite_userdata_set)
    __swig_setmethods__["group_message"] = _tox.Messenger_group_message_set
    __swig_getmethods__["group_message"] = _tox.Messenger_group_message_get
    if _newclass:group_message = _swig_property(_tox.Messenger_group_message_get, _tox.Messenger_group_message_set)
    __swig_setmethods__["group_message_userdata"] = _tox.Messenger_group_message_userdata_set
    __swig_getmethods__["group_message_userdata"] = _tox.Messenger_group_message_userdata_get
    if _newclass:group_message_userdata = _swig_property(_tox.Messenger_group_message_userdata_get, _tox.Messenger_group_message_userdata_set)
    __swig_setmethods__["group_action"] = _tox.Messenger_group_action_set
    __swig_getmethods__["group_action"] = _tox.Messenger_group_action_get
    if _newclass:group_action = _swig_property(_tox.Messenger_group_action_get, _tox.Messenger_group_action_set)
    __swig_setmethods__["group_action_userdata"] = _tox.Messenger_group_action_userdata_set
    __swig_getmethods__["group_action_userdata"] = _tox.Messenger_group_action_userdata_get
    if _newclass:group_action_userdata = _swig_property(_tox.Messenger_group_action_userdata_get, _tox.Messenger_group_action_userdata_set)
    __swig_setmethods__["group_namelistchange"] = _tox.Messenger_group_namelistchange_set
    __swig_getmethods__["group_namelistchange"] = _tox.Messenger_group_namelistchange_get
    if _newclass:group_namelistchange = _swig_property(_tox.Messenger_group_namelistchange_get, _tox.Messenger_group_namelistchange_set)
    __swig_setmethods__["group_namelistchange_userdata"] = _tox.Messenger_group_namelistchange_userdata_set
    __swig_getmethods__["group_namelistchange_userdata"] = _tox.Messenger_group_namelistchange_userdata_get
    if _newclass:group_namelistchange_userdata = _swig_property(_tox.Messenger_group_namelistchange_userdata_get, _tox.Messenger_group_namelistchange_userdata_set)
    __swig_setmethods__["file_sendrequest"] = _tox.Messenger_file_sendrequest_set
    __swig_getmethods__["file_sendrequest"] = _tox.Messenger_file_sendrequest_get
    if _newclass:file_sendrequest = _swig_property(_tox.Messenger_file_sendrequest_get, _tox.Messenger_file_sendrequest_set)
    __swig_setmethods__["file_sendrequest_userdata"] = _tox.Messenger_file_sendrequest_userdata_set
    __swig_getmethods__["file_sendrequest_userdata"] = _tox.Messenger_file_sendrequest_userdata_get
    if _newclass:file_sendrequest_userdata = _swig_property(_tox.Messenger_file_sendrequest_userdata_get, _tox.Messenger_file_sendrequest_userdata_set)
    __swig_setmethods__["file_filecontrol"] = _tox.Messenger_file_filecontrol_set
    __swig_getmethods__["file_filecontrol"] = _tox.Messenger_file_filecontrol_get
    if _newclass:file_filecontrol = _swig_property(_tox.Messenger_file_filecontrol_get, _tox.Messenger_file_filecontrol_set)
    __swig_setmethods__["file_filecontrol_userdata"] = _tox.Messenger_file_filecontrol_userdata_set
    __swig_getmethods__["file_filecontrol_userdata"] = _tox.Messenger_file_filecontrol_userdata_get
    if _newclass:file_filecontrol_userdata = _swig_property(_tox.Messenger_file_filecontrol_userdata_get, _tox.Messenger_file_filecontrol_userdata_set)
    __swig_setmethods__["file_filedata"] = _tox.Messenger_file_filedata_set
    __swig_getmethods__["file_filedata"] = _tox.Messenger_file_filedata_get
    if _newclass:file_filedata = _swig_property(_tox.Messenger_file_filedata_get, _tox.Messenger_file_filedata_set)
    __swig_setmethods__["file_filedata_userdata"] = _tox.Messenger_file_filedata_userdata_set
    __swig_getmethods__["file_filedata_userdata"] = _tox.Messenger_file_filedata_userdata_get
    if _newclass:file_filedata_userdata = _swig_property(_tox.Messenger_file_filedata_userdata_get, _tox.Messenger_file_filedata_userdata_set)
    __swig_setmethods__["msi_packet"] = _tox.Messenger_msi_packet_set
    __swig_getmethods__["msi_packet"] = _tox.Messenger_msi_packet_get
    if _newclass:msi_packet = _swig_property(_tox.Messenger_msi_packet_get, _tox.Messenger_msi_packet_set)
    __swig_setmethods__["msi_packet_userdata"] = _tox.Messenger_msi_packet_userdata_set
    __swig_getmethods__["msi_packet_userdata"] = _tox.Messenger_msi_packet_userdata_get
    if _newclass:msi_packet_userdata = _swig_property(_tox.Messenger_msi_packet_userdata_get, _tox.Messenger_msi_packet_userdata_set)
    def __init__(self): 
        this = _tox.new_Messenger()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _tox.delete_Messenger
    __del__ = lambda self : None;
Messenger_swigregister = _tox.Messenger_swigregister
Messenger_swigregister(Messenger)


def getaddress(*args):
  return _tox.getaddress(*args)
getaddress = _tox.getaddress

def m_addfriend(*args):
  return _tox.m_addfriend(*args)
m_addfriend = _tox.m_addfriend

def m_addfriend_norequest(*args):
  return _tox.m_addfriend_norequest(*args)
m_addfriend_norequest = _tox.m_addfriend_norequest

def getfriend_id(*args):
  return _tox.getfriend_id(*args)
getfriend_id = _tox.getfriend_id

def getclient_id(*args):
  return _tox.getclient_id(*args)
getclient_id = _tox.getclient_id

def m_delfriend(*args):
  return _tox.m_delfriend(*args)
m_delfriend = _tox.m_delfriend

def m_get_friend_connectionstatus(*args):
  return _tox.m_get_friend_connectionstatus(*args)
m_get_friend_connectionstatus = _tox.m_get_friend_connectionstatus

def m_friend_exists(*args):
  return _tox.m_friend_exists(*args)
m_friend_exists = _tox.m_friend_exists

def m_sendmessage(*args):
  return _tox.m_sendmessage(*args)
m_sendmessage = _tox.m_sendmessage

def m_sendmessage_withid(*args):
  return _tox.m_sendmessage_withid(*args)
m_sendmessage_withid = _tox.m_sendmessage_withid

def m_sendaction(*args):
  return _tox.m_sendaction(*args)
m_sendaction = _tox.m_sendaction

def m_sendaction_withid(*args):
  return _tox.m_sendaction_withid(*args)
m_sendaction_withid = _tox.m_sendaction_withid

def setfriendname(*args):
  return _tox.setfriendname(*args)
setfriendname = _tox.setfriendname

def setname(*args):
  return _tox.setname(*args)
setname = _tox.setname

def getself_name(*args):
  return _tox.getself_name(*args)
getself_name = _tox.getself_name

def getname(*args):
  return _tox.getname(*args)
getname = _tox.getname

def m_get_name_size(*args):
  return _tox.m_get_name_size(*args)
m_get_name_size = _tox.m_get_name_size

def m_get_self_name_size(*args):
  return _tox.m_get_self_name_size(*args)
m_get_self_name_size = _tox.m_get_self_name_size

def m_set_statusmessage(*args):
  return _tox.m_set_statusmessage(*args)
m_set_statusmessage = _tox.m_set_statusmessage

def m_set_userstatus(*args):
  return _tox.m_set_userstatus(*args)
m_set_userstatus = _tox.m_set_userstatus

def m_get_statusmessage_size(*args):
  return _tox.m_get_statusmessage_size(*args)
m_get_statusmessage_size = _tox.m_get_statusmessage_size

def m_get_self_statusmessage_size(*args):
  return _tox.m_get_self_statusmessage_size(*args)
m_get_self_statusmessage_size = _tox.m_get_self_statusmessage_size

def m_copy_statusmessage(*args):
  return _tox.m_copy_statusmessage(*args)
m_copy_statusmessage = _tox.m_copy_statusmessage

def m_copy_self_statusmessage(*args):
  return _tox.m_copy_self_statusmessage(*args)
m_copy_self_statusmessage = _tox.m_copy_self_statusmessage

def m_get_userstatus(*args):
  return _tox.m_get_userstatus(*args)
m_get_userstatus = _tox.m_get_userstatus

def m_get_self_userstatus(*args):
  return _tox.m_get_self_userstatus(*args)
m_get_self_userstatus = _tox.m_get_self_userstatus

def m_get_last_online(*args):
  return _tox.m_get_last_online(*args)
m_get_last_online = _tox.m_get_last_online

def m_set_usertyping(*args):
  return _tox.m_set_usertyping(*args)
m_set_usertyping = _tox.m_set_usertyping

def m_get_istyping(*args):
  return _tox.m_get_istyping(*args)
m_get_istyping = _tox.m_get_istyping

def m_set_sends_receipts(*args):
  return _tox.m_set_sends_receipts(*args)
m_set_sends_receipts = _tox.m_set_sends_receipts

def m_callback_friendrequest(*args):
  return _tox.m_callback_friendrequest(*args)
m_callback_friendrequest = _tox.m_callback_friendrequest

def m_callback_friendmessage(*args):
  return _tox.m_callback_friendmessage(*args)
m_callback_friendmessage = _tox.m_callback_friendmessage

def m_callback_action(*args):
  return _tox.m_callback_action(*args)
m_callback_action = _tox.m_callback_action

def m_callback_namechange(*args):
  return _tox.m_callback_namechange(*args)
m_callback_namechange = _tox.m_callback_namechange

def m_callback_statusmessage(*args):
  return _tox.m_callback_statusmessage(*args)
m_callback_statusmessage = _tox.m_callback_statusmessage

def m_callback_userstatus(*args):
  return _tox.m_callback_userstatus(*args)
m_callback_userstatus = _tox.m_callback_userstatus

def m_callback_typingchange(*args):
  return _tox.m_callback_typingchange(*args)
m_callback_typingchange = _tox.m_callback_typingchange

def m_callback_read_receipt(*args):
  return _tox.m_callback_read_receipt(*args)
m_callback_read_receipt = _tox.m_callback_read_receipt

def m_callback_connectionstatus(*args):
  return _tox.m_callback_connectionstatus(*args)
m_callback_connectionstatus = _tox.m_callback_connectionstatus

def m_callback_connectionstatus_internal_av(*args):
  return _tox.m_callback_connectionstatus_internal_av(*args)
m_callback_connectionstatus_internal_av = _tox.m_callback_connectionstatus_internal_av

def m_callback_group_invite(*args):
  return _tox.m_callback_group_invite(*args)
m_callback_group_invite = _tox.m_callback_group_invite

def m_callback_group_message(*args):
  return _tox.m_callback_group_message(*args)
m_callback_group_message = _tox.m_callback_group_message

def m_callback_group_action(*args):
  return _tox.m_callback_group_action(*args)
m_callback_group_action = _tox.m_callback_group_action

def m_callback_group_namelistchange(*args):
  return _tox.m_callback_group_namelistchange(*args)
m_callback_group_namelistchange = _tox.m_callback_group_namelistchange

def add_groupchat(*args):
  return _tox.add_groupchat(*args)
add_groupchat = _tox.add_groupchat

def del_groupchat(*args):
  return _tox.del_groupchat(*args)
del_groupchat = _tox.del_groupchat

def m_group_peername(*args):
  return _tox.m_group_peername(*args)
m_group_peername = _tox.m_group_peername

def invite_friend(*args):
  return _tox.invite_friend(*args)
invite_friend = _tox.invite_friend

def join_groupchat(*args):
  return _tox.join_groupchat(*args)
join_groupchat = _tox.join_groupchat

def group_message_send(*args):
  return _tox.group_message_send(*args)
group_message_send = _tox.group_message_send

def group_action_send(*args):
  return _tox.group_action_send(*args)
group_action_send = _tox.group_action_send

def group_number_peers(*args):
  return _tox.group_number_peers(*args)
group_number_peers = _tox.group_number_peers

def group_names(*args):
  return _tox.group_names(*args)
group_names = _tox.group_names

def callback_file_sendrequest(*args):
  return _tox.callback_file_sendrequest(*args)
callback_file_sendrequest = _tox.callback_file_sendrequest

def callback_file_control(*args):
  return _tox.callback_file_control(*args)
callback_file_control = _tox.callback_file_control

def callback_file_data(*args):
  return _tox.callback_file_data(*args)
callback_file_data = _tox.callback_file_data

def file_sendrequest(*args):
  return _tox.file_sendrequest(*args)
file_sendrequest = _tox.file_sendrequest

def new_filesender(*args):
  return _tox.new_filesender(*args)
new_filesender = _tox.new_filesender

def file_control(*args):
  return _tox.file_control(*args)
file_control = _tox.file_control

def file_data(*args):
  return _tox.file_data(*args)
file_data = _tox.file_data

def file_dataremaining(*args):
  return _tox.file_dataremaining(*args)
file_dataremaining = _tox.file_dataremaining

def m_callback_msi_packet(*args):
  return _tox.m_callback_msi_packet(*args)
m_callback_msi_packet = _tox.m_callback_msi_packet

def m_msi_packet(*args):
  return _tox.m_msi_packet(*args)
m_msi_packet = _tox.m_msi_packet

def custom_lossy_packet_registerhandler(*args):
  return _tox.custom_lossy_packet_registerhandler(*args)
custom_lossy_packet_registerhandler = _tox.custom_lossy_packet_registerhandler

def send_custom_lossy_packet(*args):
  return _tox.send_custom_lossy_packet(*args)
send_custom_lossy_packet = _tox.send_custom_lossy_packet

def custom_lossless_packet_registerhandler(*args):
  return _tox.custom_lossless_packet_registerhandler(*args)
custom_lossless_packet_registerhandler = _tox.custom_lossless_packet_registerhandler

def send_custom_lossless_packet(*args):
  return _tox.send_custom_lossless_packet(*args)
send_custom_lossless_packet = _tox.send_custom_lossless_packet

def new_messenger(*args):
  return _tox.new_messenger(*args)
new_messenger = _tox.new_messenger

def kill_messenger(*args):
  return _tox.kill_messenger(*args)
kill_messenger = _tox.kill_messenger

def do_messenger(*args):
  return _tox.do_messenger(*args)
do_messenger = _tox.do_messenger

def messenger_run_interval(*args):
  return _tox.messenger_run_interval(*args)
messenger_run_interval = _tox.messenger_run_interval

def messenger_size(*args):
  return _tox.messenger_size(*args)
messenger_size = _tox.messenger_size

def messenger_save(*args):
  return _tox.messenger_save(*args)
messenger_save = _tox.messenger_save

def messenger_load(*args):
  return _tox.messenger_load(*args)
messenger_load = _tox.messenger_load

def count_friendlist(*args):
  return _tox.count_friendlist(*args)
count_friendlist = _tox.count_friendlist

def get_num_online_friends(*args):
  return _tox.get_num_online_friends(*args)
get_num_online_friends = _tox.get_num_online_friends

def copy_friendlist(*args):
  return _tox.copy_friendlist(*args)
copy_friendlist = _tox.copy_friendlist

def get_friendlist(*args):
  return _tox.get_friendlist(*args)
get_friendlist = _tox.get_friendlist

def count_chatlist(*args):
  return _tox.count_chatlist(*args)
count_chatlist = _tox.count_chatlist

def copy_chatlist(*args):
  return _tox.copy_chatlist(*args)
copy_chatlist = _tox.copy_chatlist
# This file is compatible with both classic and new-style classes.


